# Generated by Django 3.1.3 on 2021-01-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210105_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item',
            new_name='for_sale',
        ),
    ]
