# Generated by Django 3.1.3 on 2021-01-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210105_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='for_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opinions', to='auctions.listing'),
        ),
    ]
