# Generated by Django 3.1.3 on 2021-01-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210105_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('AN', 'Antiques'), ('AR', 'Art'), ('BO', 'Books'), ('CL', 'Clothing'), ('FI', 'Film'), ('MU', 'Music'), ('GA', 'Games')], default='AN', max_length=2),
            preserve_default=False,
        ),
    ]
