# Generated by Django 3.1.3 on 2022-02-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210107_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
