# Generated by Django 3.1.3 on 2022-02-07 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20220207_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='watching',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='user',
            name='watching',
            field=models.ManyToManyField(related_name='watchlist', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='user',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top', to='auctions.listing'),
        ),
    ]
